repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      exclude: pydhcplib/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: ["--ignore=W503,E203", --max-line-length=88]
    - id: check-json
    - id: check-yaml
    - id: pretty-format-json
      args: [--autofix, --top-keys=_default_]
    - id: detect-private-key
    - id: check-added-large-files

